FROM golang:1.26 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app/main .


FROM alpine:3.19

WORKDIR /app
COPY --from=builder /app/main .


EXPOSE 8080

CMD ["./main"]