// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_queries.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countPosts = `-- name: CountPosts :one
SELECT COUNT(*) AS count
FROM posts
`

func (q *Queries) CountPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsByUserId = `-- name: CountPostsByUserId :one
SELECT COUNT(*) AS count
FROM posts
WHERE user_id = $1
`

func (q *Queries) CountPostsByUserId(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPostsByUserId, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, url,title, content, user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, url, title, content, user_id, created_at, updated_at
`

type CreatePostParams struct {
	ID      uuid.UUID
	Url     sql.NullString
	Title   string
	Content string
	UserID  uuid.UUID
}

type CreatePostRow struct {
	ID        uuid.UUID
	Url       sql.NullString
	Title     string
	Content   string
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.Url,
		arg.Title,
		arg.Content,
		arg.UserID,
	)
	var i CreatePostRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePostById = `-- name: DeletePostById :one
DELETE FROM posts
WHERE id = $1
RETURNING id, url, title, content, user_id, created_at, updated_at
`

type DeletePostByIdRow struct {
	ID        uuid.UUID
	Url       sql.NullString
	Title     string
	Content   string
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) DeletePostById(ctx context.Context, id uuid.UUID) (DeletePostByIdRow, error) {
	row := q.db.QueryRowContext(ctx, deletePostById, id)
	var i DeletePostByIdRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostById = `-- name: GetPostById :one
SELECT id, url, title, content, user_id, created_at, updated_at
FROM posts
WHERE id = $1
`

type GetPostByIdRow struct {
	ID        uuid.UUID
	Url       sql.NullString
	Title     string
	Content   string
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetPostById(ctx context.Context, id uuid.UUID) (GetPostByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getPostById, id)
	var i GetPostByIdRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostsByTitle = `-- name: GetPostsByTitle :many
SELECT id, url, title, content, user_id, created_at, updated_at
FROM posts
WHERE title ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
`

type GetPostsByTitleRow struct {
	ID        uuid.UUID
	Url       sql.NullString
	Title     string
	Content   string
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetPostsByTitle(ctx context.Context, dollar_1 sql.NullString) ([]GetPostsByTitleRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByTitle, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsByTitleRow
	for rows.Next() {
		var i GetPostsByTitleRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsByUserId = `-- name: GetPostsByUserId :many
SELECT id, url, title, content, user_id, created_at, updated_at
FROM posts
WHERE user_id = $1
ORDER BY created_at DESC
`

type GetPostsByUserIdRow struct {
	ID        uuid.UUID
	Url       sql.NullString
	Title     string
	Content   string
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetPostsByUserId(ctx context.Context, userID uuid.UUID) ([]GetPostsByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsByUserIdRow
	for rows.Next() {
		var i GetPostsByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIdByPostId = `-- name: GetUserIdByPostId :one
SELECT user_id
FROM posts
WHERE id = $1
`

func (q *Queries) GetUserIdByPostId(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserIdByPostId, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const listNPosts = `-- name: ListNPosts :many
SELECT id, url, title, content, user_id, created_at, updated_at
FROM posts
ORDER BY created_at DESC
LIMIT $1
`

type ListNPostsRow struct {
	ID        uuid.UUID
	Url       sql.NullString
	Title     string
	Content   string
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) ListNPosts(ctx context.Context, limit int32) ([]ListNPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNPosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNPostsRow
	for rows.Next() {
		var i ListNPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT id, url, title, content, user_id, created_at, updated_at
FROM posts
ORDER BY created_at DESC
`

type ListPostsRow struct {
	ID        uuid.UUID
	Url       sql.NullString
	Title     string
	Content   string
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) ListPosts(ctx context.Context) ([]ListPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsRow
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostById = `-- name: UpdatePostById :one
UPDATE posts
SET title = $2, content = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, url, title, content, user_id, created_at, updated_at
`

type UpdatePostByIdParams struct {
	ID      uuid.UUID
	Title   string
	Content string
}

type UpdatePostByIdRow struct {
	ID        uuid.UUID
	Url       sql.NullString
	Title     string
	Content   string
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) UpdatePostById(ctx context.Context, arg UpdatePostByIdParams) (UpdatePostByIdRow, error) {
	row := q.db.QueryRowContext(ctx, updatePostById, arg.ID, arg.Title, arg.Content)
	var i UpdatePostByIdRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostByUrl = `-- name: getPostByUrl :one
SELECT id, url, title, content, user_id, created_at, updated_at
FROM posts
WHERE url = $1
`

type getPostByUrlRow struct {
	ID        uuid.UUID
	Url       sql.NullString
	Title     string
	Content   string
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) getPostByUrl(ctx context.Context, url sql.NullString) (getPostByUrlRow, error) {
	row := q.db.QueryRowContext(ctx, getPostByUrl, url)
	var i getPostByUrlRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
